#!/usr/bin/env bash

####################################
# Place this file in /usr/local/sbin
####################################
BASEDIR=/home/ubuntu/kershner
DJANGODIR=$BASEDIR/kershner
VENVDIR=$BASEDIR/venv
PIP="$VENVDIR/bin/pip"
PYTHON="$VENVDIR/bin/python"
PROD_SETTINGS="--settings=site_config.settings.prod"

# react apps
COLOR_DOODLE_DIR=$BASEDIR/apps/color_doodle/react_frontend

echo '==========[ DEPLOYING KERSHNER.ORG ]=========='
echo ''

echo '==========[ Stopping supervisor ]=========='
sudo service supervisor stop
echo ''

echo '==========[ Reverting repo to HEAD (git checkout .) ]=========='
cd $DJANGODIR
git checkout .
echo ''

echo '==========[ git pull ]=========='
git pull origin master
echo ''

echo '==========[ Installing Python requirements ]=========='
$PIP install -q -r $BASEDIR/requirements.txt --no-cache-dir
echo ''

echo '==========[ Migrating DB ]=========='
$PYTHON $BASEDIR/manage.py makemigrations $PROD_SETTINGS
$PYTHON $BASEDIR/manage.py migrate $PROD_SETTINGS
echo ''


echo '==========[ Compiling front end assets (react etc) ]=========='
cd $COLOR_DOODLE_DIR
npm install
npm run build-prod

echo '==========[ Restarting supervisor ]=========='
sudo service supervisor restart
echo ''

echo '==========[ Web server should be back online now... ]=========='
echo ''

echo '==========[ Collecting static files ]=========='
$PYTHON $BASEDIR/manage.py collectstatic $PROD_SETTINGS --noinput --ignore=node_modules
echo ''

echo '==========[ Deploy Complete! ]=========='
echo ''