#!/usr/bin/env bash

set -e

####################################
# Place this file in /usr/local/sbin
####################################
BASEDIR=/home/ubuntu/kershner
DJANGODIR=$BASEDIR/kershner
VENVDIR=$BASEDIR/venv
PIP="$VENVDIR/bin/pip"
PYTHON="$VENVDIR/bin/python"
PROD_SETTINGS="--settings=site_config.settings.prod"
SKIP_COLLECTSTATIC=false
SKIP_CLOUDFRONT_PURGE=false
SUPERVISOR_STOPPED=false

restore_supervisor() {
    if [ "$SUPERVISOR_STOPPED" = true ]; then
        echo '==========[ Restoring supervisor after deploy failure ]=========='
        sudo service supervisor start
    fi
}

trap restore_supervisor EXIT

for DEPLOY_OPTION in "$@"; do
    case "$DEPLOY_OPTION" in
        --skip-collectstatic) SKIP_COLLECTSTATIC=true ;;
        --skip-cloudfront-purge) SKIP_CLOUDFRONT_PURGE=true ;;
        --help)
            echo "Usage: kershner-deploy [--skip-collectstatic] [--skip-cloudfront-purge]"
            exit 0
            ;;
        *)
            echo "Unknown option: $DEPLOY_OPTION" >&2
            exit 2
            ;;
    esac
done

# react apps
REACT_BASE_DIR=$BASEDIR/static/react-apps
COLOR_DOODLE_DIR=$REACT_BASE_DIR/colorDoodle
MUSIC_PLAYER_DIR=$REACT_BASE_DIR/musicPlayer

echo '==========[ DEPLOYING KERSHNER.ORG ]=========='
echo ''

echo '==========[ Stopping supervisor ]=========='
sudo service supervisor stop
SUPERVISOR_STOPPED=true
echo ''

echo '==========[ Reverting repo to HEAD (git checkout .) ]=========='
cd $DJANGODIR
git checkout .
echo ''

echo '==========[ git pull ]=========='
git pull origin master
echo ''

echo '==========[ Installing Python requirements ]=========='
$PIP install -q -r $BASEDIR/requirements.txt --no-cache-dir
echo ''

echo '==========[ Migrating DB ]=========='
$PYTHON $BASEDIR/manage.py makemigrations $PROD_SETTINGS
$PYTHON $BASEDIR/manage.py migrate $PROD_SETTINGS
echo ''


# echo '==========[ Compiling front end assets (react etc) ]=========='
# cd $COLOR_DOODLE_DIR
# npm install
# npm run build

# cd $MUSIC_PLAYER_DIR
# npm install
# npm run build

if [ "$SKIP_COLLECTSTATIC" = false ]; then
    echo '==========[ Collecting static files ]=========='
    $PYTHON $BASEDIR/manage.py collectstatic $PROD_SETTINGS --noinput --ignore=node_modules
    echo ''
fi

if [ "$SKIP_CLOUDFRONT_PURGE" = false ]; then
    echo '==========[ Invalidating CloudFront ]=========='
    $PYTHON $BASEDIR/manage.py invalidate_cloudfront $PROD_SETTINGS
    echo ''
fi

echo '==========[ Restarting supervisor ]=========='
sudo service supervisor restart
SUPERVISOR_STOPPED=false
echo ''

echo '==========[ Web server should be back online now... ]=========='
echo ''

echo '==========[ Deploy Complete! ]=========='
echo ''
trap - EXIT
