# Generated by Django 4.2 on 2026-09-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_stuff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('youtube_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('device_id', models.CharField(max_length=100)),
                ('playlist_id', models.CharField(blank=True, max_length=100)),
                ('playlist_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
