# Generated by Django 2.1.3 on 2022-10-24 00:09

import apps.whoosh.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoosh',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=apps.whoosh.models.whoosh_processed),
        ),
        migrations.AlterField(
            model_name='whoosh',
            name='source_video',
            field=models.FileField(upload_to=apps.whoosh.models.whoosh_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])]),
        ),
    ]
