# Generated by Django 3.2.16 on 2022-10-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0003_whoosh_black_and_white'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoosh',
            name='end_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='whoosh',
            name='start_time',
            field=models.CharField(blank=True, default='00:00:00', max_length=20, null=True),
        ),
    ]
