# Generated by Django 3.2.16 on 2022-10-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0006_auto_20221026_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoosh',
            name='slow_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whoosh',
            name='slow_zoom',
            field=models.BooleanField(default=False),
        ),
    ]
