# Generated by Django 3.2.16 on 2022-10-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0007_auto_20221026_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whoosh',
            old_name='crop_4_3',
            new_name='portrait',
        ),
    ]
