# Generated by Django 3.2.16 on 2022-10-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0009_whoosh_uniq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoosh',
            name='uniq_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
