# Generated by Django 3.2.16 on 2022-10-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0010_alter_whoosh_uniq_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoosh',
            name='whoosh_type',
            field=models.CharField(choices=[('om', 'Ominous'), ('et', 'Ethereal')], default='om', max_length=2),
        ),
    ]
