# Generated by Django 3.2.16 on 2022-10-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0011_whoosh_whoosh_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whoosh',
            name='mute_original',
        ),
        migrations.AddField(
            model_name='whoosh',
            name='mute_source',
            field=models.BooleanField(default=False, help_text='Poop'),
        ),
        migrations.AlterField(
            model_name='whoosh',
            name='black_and_white',
            field=models.BooleanField(default=False, help_text='Poop'),
        ),
        migrations.AlterField(
            model_name='whoosh',
            name='portrait',
            field=models.BooleanField(default=False, help_text='Poop'),
        ),
        migrations.AlterField(
            model_name='whoosh',
            name='slow_motion',
            field=models.BooleanField(default=False, help_text='Poop'),
        ),
        migrations.AlterField(
            model_name='whoosh',
            name='slow_zoom',
            field=models.BooleanField(default=False, help_text='Poop'),
        ),
    ]
