# Generated by Django 3.2.16 on 2022-10-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0012_auto_20221028_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoosh',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whoosh',
            name='black_and_white',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whoosh',
            name='mute_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whoosh',
            name='portrait',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whoosh',
            name='slow_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whoosh',
            name='slow_zoom',
            field=models.BooleanField(default=False),
        ),
    ]
