# Generated by Django 3.2.16 on 2022-10-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0013_auto_20221030_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoosh',
            name='doppelgangers',
            field=models.ManyToManyField(to='whoosh.Whoosh'),
        ),
    ]
