# Generated by Django 3.2.16 on 2022-10-31 21:46

import apps.whoosh.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0015_auto_20221031_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoosh',
            name='settings_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='whoosh',
            name='source_video',
            field=models.FileField(blank=True, null=True, upload_to=apps.whoosh.models.whoosh_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])]),
        ),
    ]
