# Generated by Django 3.2.16 on 2022-11-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0018_auto_20221101_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoosh',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
