# Generated by Django 3.2.16 on 2022-11-01 23:46

import apps.whoosh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0019_whoosh_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoosh',
            name='saved_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=apps.whoosh.models.whoosh_saved),
        ),
        migrations.AddField(
            model_name='whoosh',
            name='saved_video',
            field=models.FileField(blank=True, null=True, upload_to=apps.whoosh.models.whoosh_saved),
        ),
    ]
