# Generated by Django 3.2.16 on 2022-11-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0021_auto_20221102_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoosh',
            name='uniq_id',
            field=models.CharField(max_length=100),
        ),
    ]
