# Generated by Django 3.2.16 on 2022-11-12 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0024_whoosh_honeypot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whoosh',
            old_name='honeypot',
            new_name='hidden',
        ),
    ]
