# Generated by Django 3.2.16 on 2022-11-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0025_rename_honeypot_whoosh_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoosh',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
