# Generated by Django 4.1.3 on 2022-11-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoosh', '0026_whoosh_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoosh',
            name='reverse',
            field=models.BooleanField(default=False),
        ),
    ]
