# Generated by Django 4.2 on 2026-06-20 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'game session',
                'verbose_name_plural': 'game sessions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SessionCharacterStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=100)),
                ('entries', models.PositiveIntegerField(default=0)),
                ('text_messages', models.PositiveIntegerField(default=0)),
                ('cards', models.PositiveIntegerField(default=0)),
                ('rolls', models.PositiveIntegerField(default=0)),
                ('d20_rolls', models.PositiveIntegerField(default=0)),
                ('d20_total', models.IntegerField(default=0)),
                ('nat20s', models.PositiveIntegerField(default=0)),
                ('nat1s', models.PositiveIntegerField(default=0)),
                ('attacks', models.PositiveIntegerField(default=0)),
                ('checks', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('damage_rolls', models.PositiveIntegerField(default=0)),
                ('damage_total', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_stats', to='roll20_stats.gamesession')),
            ],
            options={
                'verbose_name': 'session character stats',
                'verbose_name_plural': 'session character stats',
                'ordering': ['-session__date', 'character'],
                'unique_together': {('session', 'character')},
            },
        ),
        migrations.CreateModel(
            name='Roll20Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_hash', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('sender', models.CharField(blank=True, max_length=100)),
                ('character', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('text', 'Text'), ('card', 'Card'), ('roll', 'Roll'), ('attack', 'Attack'), ('damage', 'Damage'), ('check', 'Check'), ('save', 'Save')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('dice', models.CharField(blank=True, max_length=200)),
                ('roll', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='roll20_stats.gamesession')),
                ('session_character_stats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='roll20_stats.sessioncharacterstats')),
            ],
            options={
                'verbose_name': 'Roll20 message',
                'verbose_name_plural': 'Roll20 messages',
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='roll20message',
            index=models.Index(fields=['session', 'character'], name='roll20_stat_session_8ffda0_idx'),
        ),
        migrations.AddIndex(
            model_name='roll20message',
            index=models.Index(fields=['timestamp'], name='roll20_stat_timesta_4d0dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='roll20message',
            index=models.Index(fields=['type'], name='roll20_stat_type_a12886_idx'),
        ),
    ]
