# Generated by Django 2.1.3 on 2018-12-09 02:13

from django.db import migrations, models
import apps.song


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.song.models.song_upload)),
                ('thumbnail', models.ImageField(upload_to=apps.song.models.song_thumbnail_upload)),
                ('type', models.CharField(choices=[('SO', 'Song'), ('LO', 'Loop')], default='LO', max_length=2)),
                ('plays', models.IntegerField(default=0)),
            ],
        ),
    ]
