# Generated by Django 2.1.3 on 2018-12-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20181208_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
