# Generated by Django 2.1.3 on 2018-12-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20181209_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
