# Generated by Django 2.1.3 on 2019-05-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_song_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='plays',
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.CharField(blank=True, default='Unknown', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='type',
            field=models.CharField(choices=[('SO', 'Song'), ('OL', 'Old Song'), ('LO', 'Loop')], default='SO', max_length=2),
        ),
    ]
