# Generated by Django 2.1.3 on 2019-05-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_auto_20190520_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
