from django.core.exceptions import FieldDoesNotExist
from django.http import JsonResponse
from django.db import models
from django.urls import path
from django import forms


class AdminAdvancedFiltersMixin:
    advanced_filters_title = "Advanced Filters"
    advanced_filters_js = ("js/adminAdvancedFilters.js",)
    advanced_filters_css = ("css/admin-advanced-filters.css",)
    
    text_field_types = (
        models.CharField,
        models.TextField,
        models.SlugField,
        models.EmailField,
        models.URLField,
    )

    comparable_field_types = (
        models.IntegerField,
        models.FloatField,
        models.DecimalField,
        models.DateField,
        models.DateTimeField,
        models.TimeField,
    )

    @property
    def media(self):
        # Include Select2/autocomplete assets because injected admin widgets need them.
        return super().media + forms.Media(
            js=(
                "admin/js/vendor/jquery/jquery.js",
                "admin/js/vendor/select2/select2.full.js",
                "admin/js/jquery.init.js",
                "admin/js/autocomplete.js",
                *self.advanced_filters_js,
            ),
            css={
                "screen": (
                    "admin/css/vendor/select2/select2.css",
                    "admin/css/autocomplete.css",
                    *self.advanced_filters_css,
                ),
            },
        )

    def get_urls(self):
        # Adds one endpoint per ModelAdmin using this mixin.
        opts = self.model._meta

        return [
            path(
                "advanced-filters/",
                self.admin_site.admin_view(self.advanced_filters_view),
                name=f"{opts.app_label}_{opts.model_name}_advanced_filters",
            ),
            *super().get_urls(),
        ]

    def advanced_filters_view(self, request):
        # GET returns field config.
        if request.method == "GET":
            return JsonResponse(self.get_advanced_filters_config(request))

        return JsonResponse({"error": "Unsupported method."}, status=405)

    def get_advanced_filters_config(self, request):
        # Returns field metadata and server-rendered widgets for the modal.
        form = self.get_form(request)()
        fields = []

        for field_name in self.get_advanced_filters_field_names(request):
            model_field = self.get_model_field(field_name)
            if model_field is None:
                continue

            form_field = self.get_advanced_filters_form_field(request, form, field_name, model_field)
            if form_field is None:
                continue

            bound_field = forms.BoundField(form, form_field, field_name)

            fields.append(
                {
                    "name": field_name,
                    "label": str(form_field.label or model_field.verbose_name or field_name),
                    "html": bound_field.as_widget(attrs={"id": f"id_{field_name}"}),
                    "lookups": self.get_advanced_filters_lookups(model_field),
                    "input_type": self.get_advanced_filters_input_type(model_field),
                }
            )

        return {
            "title": self.advanced_filters_title,
            "fields": fields,
        }

    def lookup_allowed(self, lookup, value):
        # Allows direct changelist query params generated by the advanced filter modal.
        if self.advanced_filter_lookup_allowed(lookup):
            return True

        return super().lookup_allowed(lookup, value)

    def advanced_filter_lookup_allowed(self, lookup):
        # Validates advanced filter lookups against the same field/lookup allowlist used by the UI.
        parts = lookup.split("__")

        for index in range(len(parts), 0, -1):
            field_name = "__".join(parts[:index])
            model_field = self.get_model_field(field_name)
            if model_field is None:
                continue

            lookup_name = "__".join(parts[index:]) or "exact"
            return lookup_name in self.get_advanced_filters_lookups(model_field)

        return False

    def get_advanced_filters_field_names(self, request):
        # Uses ModelAdmin field order, flattening row/group tuples.
        return list(self.flatten_fields(self.get_fields(request)))

    def flatten_fields(self, fields):
        # Converts nested field tuples/lists into a flat field-name sequence.
        for field in fields:
            if isinstance(field, (list, tuple)):
                yield from field
            else:
                yield field

    def get_model_field(self, field_name):
        # Safely resolves a concrete model field by name.
        try:
            return self.model._meta.get_field(field_name)
        except FieldDoesNotExist:
            return None

    def get_advanced_filters_form_field(self, request, form, field_name, model_field):
        # Prefer the ModelAdmin form field; fall back to normal admin widget creation.
        return form.fields.get(field_name) or self.formfield_for_dbfield(model_field, request=request)

    def get_advanced_filters_input_type(self, model_field):
        # Hints JS to convert date/time widgets to native browser inputs.
        if isinstance(model_field, models.DateTimeField):
            return "datetime-local"

        if isinstance(model_field, models.DateField):
            return "date"

        if isinstance(model_field, models.TimeField):
            return "time"

        return ""

    def get_advanced_filters_lookups(self, model_field):
        # Returns conservative lookup choices by field type.
        if isinstance(model_field, models.BooleanField):
            return ["exact", *self.null_lookup(model_field)]

        lookups = ["exact", "in", *self.null_lookup(model_field)]

        if isinstance(model_field, self.text_field_types):
            lookups.extend((
                "iexact",
                "contains",
                "icontains",
                "startswith",
                "istartswith",
                "endswith",
                "iendswith",
            ))

        if isinstance(model_field, self.comparable_field_types):
            lookups.extend(("gt", "gte", "lt", "lte"))

        return lookups

    def null_lookup(self, model_field):
        # Adds isnull only when the model field supports NULL.
        return ["isnull"] if model_field.null else []