# Generated by Django 4.1.3 on 2023-02-26 03:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_questions', models.CharField(choices=[('3', '3'), ('5', '5'), ('10', '10')], default='3', max_length=2)),
                ('subject', models.CharField(max_length=50)),
                ('processed', models.DateTimeField(blank=True, null=True)),
                ('model_engine', models.CharField(choices=[('text-davinci-003', 'Davinci'), ('curie', 'Curie'), ('babbage', 'Babbage'), ('ada', 'Ada')], default='text-davinci-003', max_length=20)),
                ('temperature', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('settings_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('openai_response', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='AiQuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_quiz.aiquiz')),
            ],
            options={
                'verbose_name': 'Question',
            },
        ),
        migrations.CreateModel(
            name='AiQuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_quiz.aiquizquestion')),
            ],
            options={
                'verbose_name': 'Answer',
            },
        ),
        migrations.AddConstraint(
            model_name='aiquiz',
            constraint=models.CheckConstraint(check=models.Q(('temperature__gte', 0.0), ('temperature__lte', 1.0)), name='ai_temperature_range'),
        ),
    ]
