# Generated by Django 4.1.3 on 2023-02-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquiz',
            name='num_questions',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('10', '10')], default='3', max_length=2),
        ),
    ]
