# Generated by Django 4.1.3 on 2023-02-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_quiz', '0002_alter_aiquiz_num_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiquizanswer',
            name='answer_type',
        ),
    ]
