# Generated by Django 4.2 on 2025-02-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daggerwalk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daggerwalklog',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
