# Generated by Django 4.2 on 2025-03-02 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daggerwalk', '0002_daggerwalklog_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('province', models.CharField(choices=[('High Rock', 'High Rock'), ('Hammerfell', 'Hammerfell')], max_length=100)),
                ('climate', models.CharField(choices=[('Desert', 'Desert'), ('Mountain', 'Mountain'), ('Woodlands', 'Woodlands'), ('Swamp', 'Swamp'), ('Ocean', 'Ocean'), ('Subtropical', 'Subtropical')], max_length=100)),
                ('region_index', models.IntegerField(blank=True, null=True)),
                ('multi_part', models.BooleanField(default=False)),
                ('fmap_image', models.CharField(blank=True, max_length=100, null=True)),
                ('offset_x', models.IntegerField(blank=True, null=True)),
                ('offset_y', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionMapPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmap_image', models.CharField(max_length=100)),
                ('offset_x', models.IntegerField()),
                ('offset_y', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_parts', to='daggerwalk.region')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.JSONField()),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shape', to='daggerwalk.region')),
            ],
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('capital', 'Capital'), ('town', 'Town'), ('landmark', 'Landmark'), ('dungeon', 'Dungeon')], default='town', max_length=50)),
                ('map_pixel_x', models.IntegerField()),
                ('map_pixel_y', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_interest', to='daggerwalk.region')),
            ],
            options={
                'unique_together': {('region', 'name')},
            },
        ),
    ]
