# Generated by Django 4.2 on 2025-03-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daggerwalk', '0003_region_regionmappart_provinceshape_poi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daggerwalklog',
            name='location_type',
        ),
        migrations.AddField(
            model_name='daggerwalklog',
            name='region_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='daggerwalk.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='province',
            field=models.CharField(choices=[('High Rock', 'High Rock'), ('Hammerfell', 'Hammerfell'), ('High Rock/Hammerfell', 'High Rock/Hammerfell')], max_length=100),
        ),
    ]
