# Generated by Django 4.2 on 2025-05-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daggerwalk', '0006_daggerwalklog_last_known_region'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='daggerwalklog',
            index=models.Index(fields=['created_at'], name='daggerwalk__created_e6f2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='daggerwalklog',
            index=models.Index(fields=['region'], name='daggerwalk__region_f4d486_idx'),
        ),
        migrations.AddIndex(
            model_name='daggerwalklog',
            index=models.Index(fields=['region', 'created_at'], name='daggerwalk__region_8609cc_idx'),
        ),
        migrations.AddIndex(
            model_name='daggerwalklog',
            index=models.Index(fields=['poi'], name='daggerwalk__poi_id_c2a9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='daggerwalklog',
            index=models.Index(fields=['current_song'], name='daggerwalk__current_1e1065_idx'),
        ),
        migrations.AddIndex(
            model_name='daggerwalklog',
            index=models.Index(fields=['weather'], name='daggerwalk__weather_b01dc6_idx'),
        ),
    ]
