# Generated by Django 4.2 on 2025-08-18 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daggerwalk', '0007_daggerwalklog_daggerwalk__created_e6f2ef_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCommandLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(db_index=True, max_length=50)),
                ('command', models.CharField(db_index=True, max_length=32)),
                ('args', models.TextField(blank=True, default='')),
                ('raw', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_commands', to='daggerwalk.daggerwalklog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chatcommandlog',
            index=models.Index(fields=['timestamp'], name='daggerwalk__timesta_b5cea3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatcommandlog',
            index=models.Index(fields=['user', 'timestamp'], name='daggerwalk__user_a530f4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatcommandlog',
            index=models.Index(fields=['command', 'timestamp'], name='daggerwalk__command_a565fa_idx'),
        ),
    ]
