# Generated by Django 4.2 on 2025-10-31 00:35

import apps.daggerwalk.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daggerwalk', '0009_quest_twitchuserprofile_chatcommandlog_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='discovered',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this POI was discovered', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_giver_img_number',
            field=models.PositiveSmallIntegerField(default=apps.daggerwalk.models.rand_quest_giver_img_number, help_text='1–502', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(502)]),
        ),
    ]
